// ESLint flat config for Sightline frontend.
// Plain script-tag JS (no modules): files share globals via <script> order,
// and proposal.js reads app.js exports via window.*.
import js from '@eslint/js';
import globals from 'globals';

export default [
  {
    ignores: [
      'node_modules/**',
      'static/dist/**', // minified build output — don't lint
      'static/videos/**',
      'static/firebase-config.js',
      'static/firebase-config.example.js', // example file, not real config
      'static/vendor/**', // minified third-party libs (three.min.js etc.)
    ],
  },
  js.configs.recommended,
  {
    // auth.js is an ES module (<script type="module">)
    files: ['static/auth.js'],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'module',
      globals: {
        ...globals.browser,
        ...globals.es2021,
        firebase: 'readonly',
        // Cross-file: app.js functions auth.js calls
        lockChatInput: 'readonly',
        unlockChatInput: 'readonly',
        updateRateLimitUI: 'readonly',
        updateVisibility: 'readonly',
      },
    },
  },
  {
    // Plain script-tag JS (non-module) — explicit list so auth.js (module)
    // is never parsed as script.
    files: [
      'static/app.js',
      'static/proposal/proposal-wizard.js',
      'static/proposal/proposal-render.js',
      'static/proposal/proposal-review.js',
      'static/proposal/proposal-export.js',
      'static/proposal/proposal-guided.js',
      'static/shared.js',
      'static/chat/chat-core.js',
      'static/chat/chat-obs.js',
      'static/chat/chat-list.js',
      'static/database.js',
      'static/sitrep/sitrep-pipeline.js',
      'static/sitrep/sitrep-reports.js',
      'static/sitrep/sitrep-controls.js',
      'static/admin.js',
      'static/dashboard.js',
      'static/map/map-core.js',
      'static/map/map-init.js',
      'static/bulletin.js',
      'static/landing3d.js',
      'static/advisor-chat.js',
    ],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'script',
      globals: {
        ...globals.browser,
        ...globals.es2021,
        // Libraries loaded via CDN <script> tags
        L: 'readonly',
        marked: 'readonly',
        DOMPurify: 'readonly',
        Chart: 'readonly',
        // Firebase (auth.js defines these on window)
        firebase: 'readonly',
        auth: 'writable',
        getIdToken: 'readonly',
        // Cross-file globals (plain script tags share the global scope):
        // app.js ⇄ proposal.js event-delegation functions + shared helpers
        api: 'readonly',
        toast: 'readonly',
        esc: 'readonly',
        escHtml: 'readonly',
        sanitizeHtml: 'readonly',
        switchTab: 'readonly',
        selectProposal: 'readonly',
        deleteProposalItem: 'readonly',
        generateSection: 'readonly',
        saveSectionManual: 'readonly',
        approveSection: 'readonly',
        skipSection: 'readonly',
        wizardSelectStep: 'readonly',
        createProposalFromSitrep: 'readonly',
        openDiffModal: 'readonly',
        openSmartScorecard: 'readonly',
        // More cross-file globals (auth.js, landing3d.js, proposal.js internals)
        THREE: 'readonly',
        proposalState: 'readonly',
        guidedProposalState: 'readonly',
        signOut: 'readonly',
        renderPinnedSourcesList: 'readonly',
        checkAdminStatus: 'readonly',
        updateVisibility: 'readonly',
        updateRateLimitUI: 'readonly',
        sendChatMessage: 'readonly',
        renderWizardSteps: 'readonly',
        renderSectionContent: 'readonly',
        renderMarkdown: 'readonly',
        openRagDrawer: 'readonly',
        md: 'readonly',
        guidedRequest: 'readonly',
        guidedRender: 'readonly',
        editTocNode: 'readonly',
        currentTab: 'writable',
        // Cross-file: proposal module internals (split into proposal/*.js)
        saveActiveProposal: 'readonly',
        showAdvisorMessage: 'readonly',
        exportProposalMarkdown: 'readonly',
        exportProposalPDF: 'readonly',
        getSectionContent: 'readonly',
        renderFinalReviewStep: 'readonly',
        renderJsonSection: 'readonly',
        renderProposalWorkspace: 'readonly',
        renderProposalList: 'readonly',
        PROPOSAL_STEPS: 'readonly',
        debouncedSaveProposal: 'readonly',
        // Cross-file: sitrep module internals (split into sitrep/*.js)
        deactivateSitrepItems: 'readonly',
        _currentReportData: 'writable',
        _currentReportFile: 'writable',
        buildSummarySourcesList: 'readonly',
        buildSourcesListFromArray: 'readonly',
        buildSourcesList: 'readonly',
        runProposalReview: 'readonly',
        // Module-level cross-references (script-tag global scope): states
        chatState: 'readonly',
        chatDiv: 'writable',
        chatInput: 'writable',
        sendBtn: 'writable',
        busyDot: 'writable',
        sitrepState: 'readonly',
        dbState: 'readonly',
        leafletMap: 'writable',
        leafletResizeFrame: 'writable',
        leafletResizeObserver: 'writable',
        // Module functions called across files
        toggleChatSidebar: 'readonly',
        toggleObsPanel: 'readonly',
        setObsOpen: 'readonly',
        renderObsOverview: 'readonly',
        updateObsModel: 'readonly',
        resetObsTrace: 'readonly',
        addObsLlm: 'readonly',
        finalizeObsLlm: 'readonly',
        addObsStep: 'readonly',
        finalizeObsStep: 'readonly',
        obsTraceError: 'readonly',
        renderObsFooter: 'readonly',
        refreshObsTotals: 'readonly',
        fmtTokens: 'readonly',
        applyFilters: 'readonly',
        loadChatList: 'readonly',
        initWorldMap: 'readonly',
        closeSitrepModal: 'readonly',
        closeDbModal: 'readonly',
        tagAdd: 'readonly',
        sendMessage: 'readonly',
        scheduleChunkPreview: 'readonly',
        runPipeline: 'readonly',
        openSitrepReport: 'readonly',
        openDbReport: 'readonly',
        openBulletin: 'readonly',
        leafletMarkers: 'writable',
        hideUploadModal: 'readonly',
        dashboardLoaded: 'writable',
        crisisMapData: 'writable',
        addMsg: 'readonly',
        renderTeleFooter: 'readonly',
        ADMIN_EMAIL: 'readonly',
        viewBulletinSitrep: 'readonly',
        updateUploadBtnVisibility: 'readonly',
        updateChatPlaceholder: 'readonly',
        toggleSidebarNav: 'readonly',
        toggleCard: 'readonly',
        tagRemove: 'readonly',
        tagRender: 'readonly',
        switchReportView: 'readonly',
        showSitrepView: 'readonly',
        renderSitrepReport: 'readonly',
        renderTable: 'readonly',
        renderCrisisPanelContent: 'readonly',
        renderCountryCard: 'readonly',
        openCountryCard: 'readonly',
        newChat: 'readonly',
        loadDashboard: 'readonly',
        loadCommandCenter: 'readonly',
        initAppData: 'readonly',
        initPreviewData: 'readonly',
        initPreviewLogin: 'readonly',
        getWelcomeHTML: 'readonly',
        executeDeleteChat: 'readonly',
        closeCrisisPanel: 'readonly',
        closeCountryCard: 'readonly',
        checkAdminStatus: 'readonly',
        showLoginPanel: 'readonly',
        loadBulletinList: 'readonly',
        loadAnalytics: 'readonly',
        loadAdminUsers: 'readonly',
        loadSitrepReportsList: 'readonly',
        loadStats: 'readonly',
        loadRecentReports: 'readonly',
        loadFilterOptions: 'readonly',
        loadChatSidebar: 'readonly',
        CHAT_MODELS: 'readonly',
        CUSTOM_MODELS: 'readonly',
        STEPS: 'readonly',
        askAbout: 'readonly',
        buildStepsGrid: 'readonly',
        ccStartBulletin: 'readonly',
        ccStartProposal: 'readonly',
        ccStartSitrep: 'readonly',
        clearUploadForm: 'readonly',
        confirmDeleteChat: 'readonly',
        dbFilter: 'readonly',
        deleteSitrepReport: 'readonly',
        discussSitrepWithAgent: 'readonly',
        fetchCountryDateRange: 'readonly',
        generateBulletin: 'readonly',
        hideProposalPicker: 'readonly',
        loadChatProposals: 'readonly',
        mapCountries: 'writable',
        reloadReports: 'readonly',
        renameChat: 'readonly',
        sendQuickPrompt: 'readonly',
        setUserRole: 'readonly',
        showCitationFromEl: 'readonly',
        showProposalPicker: 'readonly',
        showUploadModal: 'readonly',
        sortBy: 'readonly',
        submitUpload: 'readonly',
        scheduleWorldMapResize: 'readonly',
        loadCountryDropdown: 'readonly',
        humanizeWeekLabel: 'readonly',
      },
    },
    rules: {
      // '_'-prefixed names are intentional throwaways (destructuring, catch,
      // unused params) — don't nag about them.
      'no-unused-vars': ['warn', { argsIgnorePattern: '^_', varsIgnorePattern: '^_', caughtErrorsIgnorePattern: '^_' }],
      'no-console': ['warn', { allow: ['warn', 'error'] }],
      'no-constant-condition': ['error', { checkLoops: false }],
      // Plain script tags: files define AND consume shared globals; the
      // cross-file globals above are documentation, not redeclarations.
      'no-redeclare': 'off',
      // Module split: every file defines functions that OTHER files call at
      // runtime (global scope). "unused" within a single file is expected.
      'no-unused-vars': 'off',
      // Empty catch blocks are intentional "silently swallow" patterns
      // throughout this codebase (fetch fallbacks, optional parsing).
      'no-empty': ['error', { allowEmptyCatch: true }],
    },
  },
];
